

package AbstractProductA;



import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.GregorianCalendar;


public class Panel2 extends Panel{

    /**
     * Creates new form Panel1
     */
    public Panel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JMBG = new javax.swing.JFormattedTextField();
        SifraStomatologa = new javax.swing.JFormattedTextField();
        Usluga = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SifraIntervencije = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Kreiraj = new javax.swing.JButton();
        Promeni = new javax.swing.JButton();
        Obrisi = new javax.swing.JButton();
        Nadji = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Poruka = new javax.swing.JTextField();
        Datum = new datechooser.beans.DateChooserCombo();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JMBG.setName("JMBG"); // NOI18N
        JMBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMBGActionPerformed(evt);
            }
        });
        JMBG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JMBGKeyPressed(evt);
            }
        });
        add(JMBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 120, -1));

        SifraStomatologa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        SifraStomatologa.setDoubleBuffered(true);
        SifraStomatologa.setName("SifraStomatologa"); // NOI18N
        SifraStomatologa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SifraStomatologaKeyPressed(evt);
            }
        });
        add(SifraStomatologa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 36, -1));

        Usluga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pregled", "Popravka", "Vadjenje zuba", "Skidanje kamenca", "Stavljanje proteze", "Beljenje zuba" }));
        Usluga.setEditor(null);
        Usluga.setName("Usluga"); // NOI18N
        Usluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UslugaActionPerformed(evt);
            }
        });
        Usluga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UslugaKeyPressed(evt);
            }
        });
        add(Usluga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 160, -1));

        jLabel1.setText("JMBG:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel2.setText("Sifra stomatologa:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setText("Usluga:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        SifraIntervencije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SifraIntervencijeActionPerformed(evt);
            }
        });
        SifraIntervencije.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SifraIntervencijeKeyPressed(evt);
            }
        });
        add(SifraIntervencije, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 54, -1));

        jLabel4.setText("Sifra intervencije:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel5.setText("Datum:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        Kreiraj.setText("Kreiraj");
        add(Kreiraj, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        Promeni.setText("Promeni");
        add(Promeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        Obrisi.setText("Obrisi");
        Obrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObrisiActionPerformed(evt);
            }
        });
        add(Obrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        Nadji.setText("Nadji");
        Nadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NadjiActionPerformed(evt);
            }
        });
        add(Nadji, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel6.setText("Poruka:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 211, 45, -1));

        Poruka.setForeground(new java.awt.Color(255, 0, 0));
        Poruka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorukaActionPerformed(evt);
            }
        });
        add(Poruka, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 208, 250, -1));
        add(Datum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DentalClinic.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 450, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void JMBGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JMBGKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                SifraStomatologa.requestFocusInWindow();
          } 
    }//GEN-LAST:event_JMBGKeyPressed

    private void SifraStomatologaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SifraStomatologaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                Usluga.requestFocusInWindow();
       } // TODO add your handling code here:
    }//GEN-LAST:event_SifraStomatologaKeyPressed

    private void UslugaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UslugaKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                SifraIntervencije.requestFocus();
          } // TODO add your handling code here:
    }//GEN-LAST:event_UslugaKeyPressed

    private void SifraIntervencijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SifraIntervencijeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SifraIntervencijeActionPerformed

    private void NadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NadjiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NadjiActionPerformed

    private void PorukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PorukaActionPerformed

    private void SifraIntervencijeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SifraIntervencijeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                JMBG.requestFocusInWindow();
          }
    }//GEN-LAST:event_SifraIntervencijeKeyPressed

    private void ObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObrisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObrisiActionPerformed

    private void UslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UslugaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UslugaActionPerformed

    private void JMBGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMBGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMBGActionPerformed

       
    @Override   
    public void setSifraIntervencije(String SifraIntervencije1) {SifraIntervencije.setText(SifraIntervencije1);}
    @Override   
    public void setSifraStomatologa(String SifraStomatologa1){SifraStomatologa.setText(SifraStomatologa1);}
    @Override   
    public void setJMBG(String BrojIndeksa1){JMBG.setText(BrojIndeksa1);}
    @Override   
    public void setUsluga(String Usluga1){Usluga.setSelectedItem(Usluga1);}

    /**
     *
     * @param Datum1
     */
    @Override   
    public void setDatum(Date Datum1) 
    {
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(Datum1);
        Datum.setSelectedDate(gc);
    } 
    @Override   
    public void setPoruka(String Poruka1) {Poruka.setText(Poruka1);} 
    

    @Override
    public String getSifraIntervencije() {return SifraIntervencije.getText();}
    @Override
    public String getSifraStomatologa (){return SifraStomatologa.getText();}
    @Override
    public String getJMBG (){return JMBG.getText();}
    @Override
    public String getUsluga (){return Usluga.getSelectedItem().toString();}
    @Override
    public Date getDatum() {return Datum.getSelectedDate().getTime();}
    
     @Override
    public javax.swing.JButton getKreiraj(){return Kreiraj;}
     @Override
    public javax.swing.JButton getPromeni(){return Promeni;}
     @Override
    public javax.swing.JButton getObrisi(){return Obrisi;}
     @Override
    public javax.swing.JButton getNadji(){return Nadji;}
     @Override
    public javax.swing.JTextField getSifraIntervencije1(){return SifraIntervencije;}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo Datum;
    private javax.swing.JFormattedTextField JMBG;
    private javax.swing.JButton Kreiraj;
    private javax.swing.JButton Nadji;
    private javax.swing.JButton Obrisi;
    private javax.swing.JTextField Poruka;
    private javax.swing.JButton Promeni;
    private javax.swing.JTextField SifraIntervencije;
    private javax.swing.JFormattedTextField SifraStomatologa;
    private javax.swing.JComboBox<String> Usluga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
