package com.journaldev.spring.model;
// Generated Jul 2, 2019 11:14:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Appointment generated by hbm2java
 */

@Entity
@Table(name="APPOINTMENT")
public class Appointment  implements java.io.Serializable {


    @Id
    @Column(name="id")
    @GeneratedValue(strategy=GenerationType.IDENTITY)
     private Integer id;
    
    
    @ManyToOne
    @JoinColumn(name="dentist", nullable=false)
     private Dentist dentist;
    
    @ManyToOne
    @JoinColumn(name="patient", nullable=false)
     private Patient patient;
    
     private Date date;
     private String note;
     private Double amount;
     private String status;
     
     //@OneToMany(mappedBy="FK_appointment", cascade={CascadeType.ALL})
     //private List<AppointmentItem> appointmentItems = new LinkedList<AppointmentItem>();

    public Appointment() {
    }

    public Appointment(Dentist dentist, Patient patient, Date date, String note, Double amount, String status, List<AppointmentItem> appointmentItems) {
       this.dentist = dentist;
       this.patient = patient;
       this.date = date;
       this.note = note;
       this.amount = amount;
       this.status = status;
       //this.appointmentItems = appointmentItems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Dentist getDentist() {
        return this.dentist;
    }
    
    public void setDentist(Dentist dentist) {
        this.dentist = dentist;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
//    public List<AppointmentItem> getAppointmentItems() {
//        return this.appointmentItems;
//    }
//    
//    public void setAppointmentItems(List<AppointmentItem> appointmentItems) {
//        this.appointmentItems = appointmentItems;
//    }




}


