package com.journaldev.spring.model;
// Generated Jul 2, 2019 11:14:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */

@Entity
@Table(name="CITY")
public class City  implements java.io.Serializable {

    @Id
    @Column(name="postNumber")
     private String postNumber;
     private String name;
    //@OneToMany(mappedBy="FK_city", cascade={CascadeType.ALL})
   //  private List<Patient> patients= new LinkedList<Patient>();

    public City() {
    }

	
    public City(String postNumber, String name) {
        this.postNumber = postNumber;
        this.name = name;
    }
    public City(String postNumber, String name, Set patients) {
       this.postNumber = postNumber;
       this.name = name;
       //this.patients = patients;
    }
   
    public String getPostNumber() {
        return this.postNumber;
    }
    
    public void setPostNumber(String postNumber) {
        this.postNumber = postNumber;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
//    public List<Patient> getPatients() {
//        return this.patients;
//    }
//    
//    public void setPatients(List<Patient> patients) {
//        this.patients = patients;
//    }




}


