package com.journaldev.spring.model;
// Generated Jul 2, 2019 11:14:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Service generated by hbm2java
 */


@Entity
@Table(name="SERVICE")
public class Service  implements java.io.Serializable {

    @Id
    @Column(name="id")
    @GeneratedValue(strategy=GenerationType.IDENTITY)
     private Integer id;
     private String name;
     private double price;
     //private List<AppointmentItem> appointmentItems = new  LinkedList<AppointmentItem>();

    public Service() {
    }

	
    public Service(String name, double price) {
        this.name = name;
        this.price = price;
    }
    public Service(String name, double price, List<AppointmentItem> appointmentItems) {
       this.name = name;
       this.price = price;
      // this.appointmentItems = appointmentItems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
//    public List<AppointmentItem> getAppointmentItems() {
//        return this.appointmentItems;
//    }
//    
//    public void setAppointmentItems(List<AppointmentItem> appointmentItems) {
//        this.appointmentItems = appointmentItems;
//    }




}


